[manifest]
version = "1.0.0"
priority = 0

# -----------------------------------
# Green Seal
# -----------------------------------

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
for i=1, hand_space do --draw cards from deckL
'''
position = "before"
payload = '''
hand_space = hand_space + G.GAME.green_seal_draws
G.GAME.green_seal_draws = 0
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
-- TARGET: main end_of_round evaluation
'''
position = "after"
payload = '''
G.GAME.green_seal_draws = 0
'''
match_indent = true
times = 1

# -----------------------------------
# Black Seal
# -----------------------------------

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, before = true})
'''
position = "before"
payload = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, hnds_pre_before = true})
'''
match_indent = true
times = 1

# -----------------------------------
# Head of Medusa
# -----------------------------------

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
    self.children.front:draw_shader('dissolve')
end
'''
position = "at"
payload = '''
    self.children.front:draw_shader('dissolve')
elseif self.ability.effect == 'Stone Card' and self.hnds_petrifying then
    self.children.front:draw_shader('dissolve')
end
'''
match_indent = true
times = 1

# -----------------------------------
# Stone Ocean
# -----------------------------------

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
-- TARGET: main scoring on played cards
'''
position = "after"
payload = '''

if card.ability.name == "Stone Card" then
    G.GAME.ante_stones_scored = G.GAME.ante_stones_scored + 1
    G.GAME.hands['hnds_stone_ocean'].l_chips = G.GAME.hands['hnds_stone_ocean'].l_chips_base + (G.GAME.hands['hnds_stone_ocean'].l_chips_scaling * G.GAME.ante_stones_scored)
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
check_and_set_high_score('furthest_ante', G.GAME.round_resets.ante)
'''
position = "after"
payload = '''
G.GAME.ante_stones_scored = 0
G.GAME.hands['hnds_stone_ocean'].l_chips = G.GAME.hands['hnds_stone_ocean'].l_chips_base
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif _c.set == 'Planet' then
        loc_vars = {
            G.GAME.hands[cfg.hand_type].level,localize(cfg.hand_type, 'poker_hands'), G.GAME.hands[cfg.hand_type].l_mult, G.GAME.hands[cfg.hand_type].l_chips,
            colours = {(G.GAME.hands[cfg.hand_type].level==1 and G.C.UI.TEXT_DARK or G.C.HAND_LEVELS[math.min(7, G.GAME.hands[cfg.hand_type].level)])}
        }
'''
position = "at"
payload = '''
elseif _c.set == 'Planet' then
    if _c.key == "c_hnds_makemake" then
        loc_vars = {
            G.GAME.hands[cfg.hand_type].level,localize(cfg.hand_type, 'poker_hands'), G.GAME.hands[cfg.hand_type].l_mult, G.GAME.hands[cfg.hand_type].l_chips,
            G.GAME.ante_stones_scored, G.GAME.hands[cfg.hand_type].l_chips_scaling,
            colours = {(G.GAME.hands[cfg.hand_type].level==1 and G.C.UI.TEXT_DARK or G.C.HAND_LEVELS[math.min(7, G.GAME.hands[cfg.hand_type].level)])}
        }
    else
        loc_vars = {
            G.GAME.hands[cfg.hand_type].level,localize(cfg.hand_type, 'poker_hands'), G.GAME.hands[cfg.hand_type].l_mult, G.GAME.hands[cfg.hand_type].l_chips,
            colours = {(G.GAME.hands[cfg.hand_type].level==1 and G.C.UI.TEXT_DARK or G.C.HAND_LEVELS[math.min(7, G.GAME.hands[cfg.hand_type].level)])}
        }
    end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
G.GAME.hands[hand].mult = math.max(G.GAME.hands[hand].s_mult + G.GAME.hands[hand].l_mult*(G.GAME.hands[hand].level - 1), 1)
    G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
'''
position = "at"
payload = '''
G.GAME.hands[hand].mult = math.max(G.GAME.hands[hand].s_mult + G.GAME.hands[hand].l_mult*(G.GAME.hands[hand].level - 1), 1)
if hand == "hnds_stone_ocean" then
    G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].chips + G.GAME.hands[hand].l_chips*amount, 0)
else
    G.GAME.hands[hand].chips = math.max(G.GAME.hands[hand].s_chips + G.GAME.hands[hand].l_chips*(G.GAME.hands[hand].level - 1), 0)
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
local card = Card(0,0, 0.5*G.CARD_W, 0.5*G.CARD_H, G.P_CARDS[v[1]], G.P_CENTERS.c_base)
'''
position = "after"
payload = '''
if v.enhancement then
    card:set_ability(G.P_CENTERS[v.enhancement])
end
'''
match_indent = true
times = 1

# -----------------------------------
# Wholesale
# -----------------------------------

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''G.GAME.current_round.used_packs = G.GAME.current_round.used_packs or {}'''
position = 'before'
match_indent = true
payload = '''if i == 1 and G.GAME.modifiers.hnds_boosters then for _ = 1, G.GAME.modifiers.hnds_boosters do HNDS.spawn_booster() end end'''

# -----------------------------------
# Resize Booster Pack UI for new options
# -----------------------------------

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.GAME.pack_choices = self.ability.choose or self.config.center.config.choose or 1"
position = "after"
payload = '''
if G.GAME.extra_pocket_picks and G.GAME.extra_pocket_picks > 0 then
  self.ability.extra = self.ability.extra + G.GAME.extra_pocket_picks
end
'''
match_indent = true

# -----------------------------------
# Perfectionist
# -----------------------------------

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability.hands_played_at_create = G.GAME and G.GAME.hands_played or 0"
position = "after"
match_indent = true
payload = '''
if old_center and old_center.set == "Enhanced" and center.set == "Enhanced" and self.area ~= G.deck then
    if G.jokers.cards then for i = 1, #G.jokers.cards do
        if G.jokers.cards[i].config.center.key == "j_hnds_perfectionist" then
            self.ability.perma_mult = self.ability.perma_mult or 0
            self.ability.perma_mult = self.ability.perma_mult + G.P_CENTERS["j_hnds_perfectionist"].config.extra.mult
            card_eval_status_text(self, 'extra', nil, nil, nil, {message = localize('k_upgrade_ex'), colour = G.C.MULT})
            G.E_MANAGER:add_event(Event({
                func = function()
                    G.jokers.cards[i]:juice_up(0.6)
                return true end
            }))
        end
    end
    end
end
'''